---
- name: Node Exporter
  hosts: aws_ec2
  become: yes

  tasks:
   - name: update all packages
     yum:
      name: yum
      state: latest

   - name: unarchive node exporter repo
     unarchive: 
       src: https://github.com/prometheus/node_exporter/releases/download/v1.4.0/node_exporter-1.4.0.linux-amd64.tar.gz
       dest: /root 
       remote_src: yes

   - name: Copy node_exporter file to bin
     copy:
       src: /root/node_exporter-1.4.0.linux-amd64/node_exporter
       dest: /usr/local/bin
       remote_src: yes
       mode: 0755
   
   - name: copy systemd service file
     template:
       src: ~/ansible/node_exporter.service.j2 
       dest: /etc/systemd/system/node_exporter.service
       remote_src: yes
       mode: 0755

   - name: reload daemon
     command: systemctl daemon-reload

   - name: start node exporter
     systemd:
       name: node_exporter
       state: started
       enabled: yes  
       
   - name: Check if node_exporter is accessible
     uri:
       url: http://localhost:9100
       method: GET
       status_code: 200
