---
- name: Install Prometheus
  hosts: all
  become: yes

  tasks:
   - name: update all packages
     yum:
      name: yum
      state: latest

   - name: unarchive prometheus repo
     unarchive: 
       src: https://github.com/prometheus/prometheus/releases/download/v2.38.0/prometheus-2.38.0.linux-amd64.tar.gz  
       dest: /root
       remote_src: yes
       validate_certs: no     
   
   - name: Copy prometheus file to bin
     copy:
       src: /root/prometheus-2.38.0.linux-amd64/prometheus
       dest: /usr/local/bin
       remote_src: yes
       mode: 0755
       
   - name: Copy prometheus config file
     template:
       src: ~/ansible/prometheus.yml
       dest: /root/prometheus-2.38.0.linux-amd64
       remote_src: yes
       mode: 0755     

   - name: copy systemd service file
     template:
       src: ~/ansible/prometheus.service.j2 
       dest: /etc/systemd/system/prometheus.service
       remote_src: yes
       mode: 0644

   - name: reload daemon
     command: systemctl daemon-reload

   - name: start prometheus
     systemd:
       name: prometheus
       state: started
       enabled: yes
       
   - name: Check if prometheus is accessible
     uri:
       url: http://localhost:9090
       method: GET
       status_code: 200
